**Curso: Métodos Numéricos II  
Professor: Creto Augusto Vidal  
Semestre: 2020.1  
Equipe: DANIEL MAGALHÃES NUNES, ANTONIO AUGUSTO DA SILVA HOLANDA  
Tarefa 15**

**Algoritimo do Método de QR**

In [2]:
import numpy as np

In [99]:
def qr(A, erro = 1e-8, imprime=False ,k_max = 100000):
    n = A.shape[0]
    A_velha = np.copy(A)
    A_nova = np.copy(A)
    P = np.eye(n)
    val = 100
    k = 1
    while val > erro and k < k_max:
        Q, R = decomposicaoQR(A_velha)
        if imprime:
            print('-'*20)
            print('A{}={}'.format(k, (R@Q).round(3)) )
            print('-'*20)
            
        A_nova = R@Q
        
        A_velha = np.copy(A_nova)
        P = P@Q
        
        val = soma_diagonal(A_nova)
        k += 1
    
    lamb = np.diag(A_nova).reshape(n, 1)
    return P, lamb

In [100]:
def soma_diagonal(A):
    n = A.shape[0]
    s = 0
    for i in range(n):
        for j in range(n):
            if i > j:
                s += A[i, j]**2
    return s

In [101]:
def decomposicaoQR(A):
    n = A.shape[0]
    QT = np.eye(n)
    R_velha = np.copy(A)
    R_nova = np.copy(A)
    
    for j in range(0, n-1):
        for i in range(j+1, n):
            Jij = matriz_jacobi(R_velha, i , j)
            
            R_nova = Jij @ R_velha
            
            R_velha = np.copy(R_nova)
            
            QT = Jij@QT
    
    return QT.T, R_nova

In [102]:
def matriz_jacobi(A, i , j):
    theta = 0
    erro = 1e-6
    n = A.shape[0]
    Jij = np.eye(n)
    if np.abs(A[i, j]) <= erro:
        return Jij
    if np.abs(A[j, j]) <= erro:
        if np.abs(A[i, j]) < 0:
            theta = np.pi / 2
        else:
            theta = - np.pi / 2
    else:
        theta = np.arctan( -A[i, j] / A[j, j] )
        
    s = np.sin(theta)
    c = np.cos(theta)
    Jij[i, i] = c
    Jij[j, j] = c
    Jij[i, j] = s
    Jij[j, i] = -s
    
    return Jij

**1) Implemente o método QR e aplique-o sobre A para encontrar**

In [103]:
A = np.array([[40, 8, 4, 2, 1],
               [8, 30, 12, 6, 2],
               [4, 12, 20, 1, 2],
               [2, 6, 1, 25, 4],
               [1, 2, 2, 4, 5]])

In [104]:
# iii. Imprima a matriz que sai de cada varredura de Jacobi
P, lamb = qr(A, imprime=True)

--------------------
A1=[[44.027  8.123  1.174  1.237  0.1  ]
 [ 8.123 34.842  4.158  4.267  0.222]
 [ 1.174  4.158 14.147 -3.563  0.253]
 [ 1.237  4.267 -3.563 22.931  0.65 ]
 [ 0.1    0.222  0.253  0.65   4.053]]
--------------------
--------------------
A2=[[ 4.6788e+01  6.3280e+00  8.3000e-02  5.5700e-01  9.0000e-03]
 [ 6.3280e+00  3.3497e+01  3.9300e-01  2.3420e+00  2.3000e-02]
 [ 8.3000e-02  3.9300e-01  1.6632e+01 -5.9380e+00  6.2000e-02]
 [ 5.5700e-01  2.3420e+00 -5.9380e+00  1.9065e+01  1.5400e-01]
 [ 9.0000e-03  2.3000e-02  6.2000e-02  1.5400e-01  4.0180e+00]]
--------------------
--------------------
A3=[[ 4.8247e+01  4.3870e+00 -1.1000e-01  1.8600e-01  1.0000e-03]
 [ 4.3870e+00  3.2290e+01 -6.1500e-01  1.0750e+00  3.0000e-03]
 [-1.1000e-01 -6.1500e-01  2.0666e+01 -5.3010e+00  1.4000e-02]
 [ 1.8600e-01  1.0750e+00 -5.3010e+00  1.4781e+01  5.0000e-02]
 [ 1.0000e-03  3.0000e-03  1.4000e-02  5.0000e-02  4.0150e+00]]
--------------------
--------------------
A4=[[ 4.8910e+01  2.8

In [105]:
P # ii. a matriz acumulada  𝑃=𝑃1𝑃2𝑃3

array([[ 0.69806129, -0.7072859 , -0.1032788 ,  0.04132603, -0.00909572],
       [ 0.5798721 ,  0.50120397,  0.24727626, -0.59191983,  0.03206715],
       [ 0.34486642,  0.32981072,  0.3938147 ,  0.77448982, -0.13178595],
       [ 0.22686156,  0.36250912, -0.87054167,  0.15536959, -0.18745257],
       [ 0.0778445 ,  0.09139618, -0.12351165,  0.15475427,  0.97282216]])

In [106]:
lamb # i. diagonal da matriz diagonal 𝐴 barra

array([[49.38314594],
       [31.31146526],
       [23.64807948],
       [11.64242638],
       [ 4.01488294]])

In [107]:
# iv. Imprima os pares (autovalor, autovetor) da matriz A
print('Autovalores de A: \n {}'.format(lamb))
print('-'*10)
print('Autovetores de A: \n {}'.format(P))

Autovalores de A: 
 [[49.38314594]
 [31.31146526]
 [23.64807948]
 [11.64242638]
 [ 4.01488294]]
----------
Autovetores de A: 
 [[ 0.69806129 -0.7072859  -0.1032788   0.04132603 -0.00909572]
 [ 0.5798721   0.50120397  0.24727626 -0.59191983  0.03206715]
 [ 0.34486642  0.32981072  0.3938147   0.77448982 -0.13178595]
 [ 0.22686156  0.36250912 -0.87054167  0.15536959 -0.18745257]
 [ 0.0778445   0.09139618 -0.12351165  0.15475427  0.97282216]]
