**Curso: Métodos Numéricos II  
Professor: Creto Augusto Vidal  
Semestre: 2020.1  
Equipe: DANIEL MAGALHÃES NUNES, ANTONIO AUGUSTO DA SILVA HOLANDA  
Tarefa 14**

**Com a matriz A abaixo, faça o que se pede:**
$$
A = \begin{bmatrix}
40 & 8 & 4 & 2 & 1\\ 
8 &30  &12  &6  & 2 \\ 
4 & 12 & 20 & 1 & 2\\ 
2 & 6 & 1 & 25 & 4\\ 
1 & 2 & 2 & 4 & 5
\end{bmatrix}
$$

1) Implemente o método de Jacobi e aplique-o sobre A para encontrar  
i. a matriz diagonal $\bar{A}$  
ii. a matriz acumulada $P = P_1 P_2 P_3$  
iii. Imprima a matriz que sai de cada varredura de Jacobi  
iv. Imprima os pares (autovalor, autovetor) da matriz A    
v. Compare os resultados do item 3) com os resultados da Tarefa # 13  

2) Adapte o método de varredura de Jacobi para receber a matriz tridiagonal que sai do método de Householder. Neste caso, observe que:  
i. as varreduras de colunas e linhas continuam as mesmas  
ii imprima $A_{nova}$ logo após a linha $A_{nova} \leftarrow  J_{ij}^T A_{velha} J_{ij}$ e verifique se os termos que eram zero deixaram de ser zero.  
iii. depois da diagonalização, verifique que as colunas de P não são os autovetores de A.  
iv. Faça P = HP e verifique que as colunas da nova matriz P são os autovetores de A

**Algoritimo do Método de Jacobi**

In [2]:
import numpy as np

In [55]:
def jacobi(A, erro = 1e-8, imprime=False ,k_max = 100000):
    n = A.shape[0]
    A_velha = np.copy(A)
    P = np.eye(n)
    val = 100
    k = 1
    while val > erro and k < k_max:
        A_nova, J = varredura_de_jacobi(A_velha)
        if imprime:
            print('-'*20)
            print('A{}={}'.format(k, A_nova.round(3)) )
            print('-'*20)
        
        A_velha = np.copy(A_nova)
        
        P = np.dot(P, J)
        
        val = soma_diagonal(A_nova)
        k += 1
    
    lamb = np.diag(A_nova).reshape(n, 1)
    return P, lamb

In [56]:
def soma_diagonal(A):
    n = A.shape[0]
    s = 0
    for i in range(n):
        for j in range(n):
            if i > j:
                s += A[i, j]**2
    return s

In [57]:
def varredura_de_jacobi(A):
    n = A.shape[0]
    J = np.eye(n)
    
    A_velha = np.copy(A)
    A_nova = np.copy(A)
    for j in range(0, n-1):
        for i in range(j+1, n):
            Jij = matriz_jacobi(A_velha, i , j)
            A_nova = Jij.T @ A_velha @ Jij
            A_velha = np.copy(A_nova)
            J = np.dot(J, Jij)
    
    return A_nova, J

In [58]:
def matriz_jacobi(A, i , j):
    theta = 0
    erro = 1e-6
    n = A.shape[0]
    Jij = np.eye(n)
    if np.abs(A[i, j]) <= erro:
        return Jij
    
    w = ( A[j, j] - A[i, i] ) / (2*A[i, j])
    t = 0
    if w < 0:
        t = -w - np.sqrt(1 + w**2)
    else:
        t = -w + np.sqrt(1 + w**2)
        
    s = t / np.sqrt(1 + t**2)
    c = 1 / np.sqrt(1 + t**2)
    n = A.shape[0]
    Jij[i, i] = c
    Jij[j, j] = c
    Jij[i, j] = s
    Jij[j, i] = -s
    
    return Jij

**1) Implemente o método de Jacobi e aplique-o sobre A para encontrar**

In [59]:
A = np.array([[40, 8, 4, 2, 1],
               [8, 30, 12, 6, 2],
               [4, 12, 20, 1, 2],
               [2, 6, 1, 25, 4],
               [1, 2, 2, 4, 5]])

In [60]:
# iii. Imprima a matriz que sai de cada varredura de Jacobi
P, lamb = jacobi(A, imprime=True)

--------------------
A1=[[48.756  2.959 -2.017 -0.503  0.092]
 [ 2.959 31.775 -0.7    0.414  0.062]
 [-2.017 -0.7   11.778  0.391 -0.049]
 [-0.503  0.414  0.391 23.675 -0.   ]
 [ 0.092  0.062 -0.049 -0.     4.015]]
--------------------
--------------------
A2=[[ 4.9383e+01  1.1000e-02 -6.0000e-03 -1.0000e-03 -0.0000e+00]
 [ 1.1000e-02  3.1311e+01  2.4000e-02  1.0000e-03  0.0000e+00]
 [-6.0000e-03  2.4000e-02  1.1642e+01  0.0000e+00  0.0000e+00]
 [-1.0000e-03  1.0000e-03  0.0000e+00  2.3648e+01 -0.0000e+00]
 [-0.0000e+00  0.0000e+00  0.0000e+00 -0.0000e+00  4.0150e+00]]
--------------------
--------------------
A3=[[49.383 -0.     0.     0.     0.   ]
 [-0.    31.311  0.    -0.    -0.   ]
 [ 0.     0.    11.642  0.    -0.   ]
 [ 0.    -0.     0.    23.648 -0.   ]
 [ 0.    -0.    -0.    -0.     4.015]]
--------------------


In [28]:
P # ii. a matriz acumulada  𝑃=𝑃1𝑃2𝑃3

array([[ 0.69806109, -0.70728482,  0.04132603,  0.10328762, -0.00909571],
       [ 0.57987223,  0.50120069, -0.59191983, -0.24728257,  0.03206718],
       [ 0.34486652,  0.32980571,  0.77448982, -0.3938188 , -0.13178603],
       [ 0.22686169,  0.36251994,  0.15536952,  0.87053714, -0.18745258],
       [ 0.07784454,  0.09139772,  0.15475433,  0.12351049,  0.97282215]])

In [30]:
lamb # i. diagonal da matriz diagonal 𝐴 barra

array([[49.38314594],
       [31.31146526],
       [11.64242638],
       [23.64807948],
       [ 4.01488294]])

In [91]:
# iv. Imprima os pares (autovalor, autovetor) da matriz A
print('Autovalores de A: \n {}'.format(lamb))
print('-'*10)
print('Autovetores de A: \n {}'.format(P))

Autovalores de A: 
 [[49.38314594]
 [31.31146526]
 [11.64242638]
 [23.64807948]
 [ 4.01488294]]
----------
Autovetores de A: 
 [[ 0.69806109 -0.70728482  0.04132603  0.10328762 -0.00909571]
 [ 0.57987223  0.50120069 -0.59191983 -0.24728257  0.03206718]
 [ 0.34486652  0.32980571  0.77448982 -0.3938188  -0.13178603]
 [ 0.22686169  0.36251994  0.15536952  0.87053714 -0.18745258]
 [ 0.07784454  0.09139772  0.15475433  0.12351049  0.97282215]]
