**Curso: Métodos Numéricos II  
Professor: Creto Augusto Vidal  
Semestre: 2020.1  
Equipe: DANIEL MAGALHÃES NUNES, ANTONIO AUGUSTO DA SILVA HOLANDA  
Tarefa 12**

**Implemente os Algoritmos metodoDaPotenciaInverso2 e metodoDaPotenciaComDeslocamento e utilize-os, junto com o algoritmo metodoDaPotenciaRegular, para achar todos os autovalores e os autovetores correspondentes de cada uma das seguintes matrizes.**
$$
A_1 = \begin{bmatrix}
5 & 2 & 1 \\ 
2 & 3 & 1\\ 
1 & 1 & 2
\end{bmatrix}
\; \;
A_2 = \begin{bmatrix}
-14 & 1 & -2 \\ 
1 & -1 & 1\\ 
-2 & 1 & -11
\end{bmatrix}
\; \;
A_3 = \begin{bmatrix}
40 & 8 & 4 & 2 & 1\\ 
8 &30  &12  &6  & 2 \\ 
4 & 12 & 20 & 1 & 2\\ 
2 & 6 & 1 & 25 & 4\\ 
1 & 2 & 2 & 4 & 5
\end{bmatrix}
$$

**Algoritimo do Método da Potência Regular**

In [6]:
import numpy as np

def metodoDaPotenciaRegular(A, v0, epsilon = 1e-4, max_iter = 10000):
    '''
    Esta função tenta encontrar o autovalor dominante e o autovetor correspondente da matriz A,
    usando o método de potência regular com os parâmetros:
     - A: (matriz) Matriz quadrada(nxn) que se deseja encontrar o autovalor dominante e o autovetor correspondente
     - v0: (vetor) Vetor arbitrário de tamanha n = dimensão da matriz A(nxn)
     - epsilon: (float) Critério de parada do método de potência quando alterações na solução são insignificantes
     - max_iter: (int) Critério de parada definitiva, quando o metodo não encontra uma solução aceitável
    '''
    ep = 0 # step 2
    vk = np.copy(v0) # step 3
    cont = 0

    while True:
        ep_velho = ep # step 4
        vk_velho = np.copy(vk) # step 5

        x1_velho = vk_velho / np.linalg.norm(vk_velho) # step 6
        vk = A.dot(x1_velho) # step 7
        ep = np.dot(x1_velho.T, vk) # step 8

        if np.abs((ep - ep_velho)/ep) < epsilon or cont > max_iter: # step 9
            break
        cont += 1
    return ep[0][0], vk.T # step 10

**Algoritimo do Método da Potência Inverso 2**

In [7]:
def metodoDaPotenciaInverso2(A, v0, epsilon = 1e-4, max_iter = 10000):
    ep = 0 # step 2
    vk = np.copy(v0) # step 3
    cont = 0

    while True:
        ep_velho = ep # step 4
        vk_velho = np.copy(vk) # step 5

        x1_velho = vk_velho / np.linalg.norm(vk_velho) # step 6
        vk = np.dot(np.linalg.inv(A), x1_velho) # step 7
        ep = np.dot(x1_velho.T, vk) # step 8

        if np.abs((ep - ep_velho)/ep) < epsilon or cont > max_iter: # step 9
            break
        cont += 1
    ep_menor = 1/ep[0][0]
    return ep_menor, vk.T # step 10

**Algoritimo do Método da Potência com Deslocamento**

In [8]:
def metodoDaPotenciaComDeslocamento(A, v0, mu):
    A_chapeu = A - mu*np.eye(A.shape[0])
    epc, xc = metodoDaPotenciaInverso2(A_chapeu, v0)
    ep = epc + mu
    x = xc
    return ep, x

**Algoritimo do Método da Potência Completo**

In [9]:
def metodoDaPotenciaCompleto(A, v0, epsilon = 1e-4, max_iter = 10000):

    if A.shape[0] == 1:
        return A, 1
    elif A.shape[0] == 2:
        ep_maior, v_maior = metodoDaPotenciaRegular(A, v0)
        ep_menor, v_menor = metodoDaPotenciaInverso2(A, v0)
        return [ep_menor, ep_maior], [v_menor, v_maior]
    else:
        ep_maior, v_maior = metodoDaPotenciaRegular(A, v0)
        ep_menor, v_menor = metodoDaPotenciaInverso2(A, v0) 
        autovalores = [ep_menor, ep_maior]
        autovetores = [v_menor, v_maior]
        passo = (ep_maior - ep_menor) / A.shape[0]
        mu = passo
        
        while len(set(autovalores)) < A.shape[0]:
            ep, vk = metodoDaPotenciaComDeslocamento(A, v0, mu)
            autovalores.append(ep)
            autovetores.append(vk)
            mu += passo
        
        return np.array(autovalores), np.array(autovetores).reshape(A.shape)

**Encontrando os autovalores e os autovetores da matriz A1**

In [17]:
A1 = np.array([[5, 2, 1], # Definindo matriz A1
              [2, 3, 1],
              [1, 1, 2]])

v0 = np.array([1, 0, 0]).reshape(3,1) # Definindo vetor v0
ep, vk = metodoDaPotenciaCompleto(A1, v0) # Chamando do método
print('autovalores: {}'.format(ep)) # Imprimindo autovalores
print('autorvetores: {}'.format(vk)) # Imprimindo autorvetores

autovalores: [1.35431471 6.64573674 2.00000923]
autorvetores: [[ 0.10360233 -0.4683789   0.56133998]
 [ 5.35302652  3.4533028   1.89359217]
 [ 2.4460212  -2.45202768 -2.43507212]]


**Encontrando os autovalores e os autovetores da matriz A2**

In [19]:
A1 = np.array([[-14, 1, -2], # Definindo matriz A2
              [1, -1, 1],
              [-2, 1, -11]])

v0 = np.array([1, 0, 0]).reshape(3,1) # Definindo vetor v0
ep, vk = metodoDaPotenciaCompleto(A1, v0) # Chamando do método
print('autovalores: {}'.format(ep)) # Imprimindo autovalores
print('autorvetores: {}'.format(vk)) # Imprimindo autorvetores

autovalores: [ -0.85092322 -15.12693876  -0.85051072]
autorvetores: [[-0.07358802 -1.16856455 -0.10061408]
 [13.47054636 -1.42787523  6.73305501]
 [ 0.01669534  0.25452067  0.02060231]]


**Encontrando os autovalores e os autovetores da matriz A3**

In [20]:
A2 = np.array([[40, 8,  4,  2, 1], # Definindo matriz A3
              [8, 30, 12,  6, 2],
              [4, 12, 20,  1, 2],
              [2,  6,  1, 25, 4],
              [1,  2,  2,  4, 5]])

v0 = np.array([1, 0, 0, 0, 0]).reshape(5, 1) # Definindo vetor v0
ep, vk = metodoDaPotenciaCompleto(A2, v0) # Chamando do método
print('autovalores: {}'.format(ep)) # Imprimindo autovalores
print('autorvetores: {}'.format(vk)) # Imprimindo autorvetores

autovalores: [ 4.01490122 49.38110001 11.64248171 23.64910867 23.64719504]
autorvetores: [[ 2.27607236e-03 -8.12218695e-03  3.29983278e-02  4.67256217e-02
  -2.42268007e-01]
 [ 3.47063623e+01  2.84667701e+01  1.69188812e+01  1.10836677e+01
   3.81381573e+00]
 [ 1.60801951e-02 -2.30368491e-01  3.01350098e-01  6.03375712e-02
   6.09614818e-02]
 [ 1.87091979e-02 -4.40290212e-02 -7.27776209e-02  1.57984971e-01
   2.22092762e-02]
 [ 3.09042669e-02 -7.06387420e-02 -1.11182154e-01  2.42701252e-01
   3.43217938e-02]]
